import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { wrapper } from "../app/store";
import { useDispatch, useSelector } from "react-redux";
import Link from "next/link";
import { increment } from "../app/store/slices/counter";
import { setProfileData } from "../app/store/slices/profile";
import { addUser } from "../app/store/slices/user";
import { useState } from "react";

export default function Home() {
  const profile = useSelector((store) => store.profile);
  const count = useSelector((store) => store.counter.value);
  const users = useSelector((store) => store.users.list);
  const [newUser, setNewUser] = useState("");

  const dispatch = useDispatch();

  const addnewUser = () => {
    // setUsers([...users, name]);
    dispatch(addUser(newUser));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h2>{`this is redux state: ${profile.name}`}</h2>

        <p>
          navigate to
          <Link href="./profile">
            <a>profile</a>
          </Link>
        </p>
        <div>
          <button
            className="btn btn-primary m-3"
            onClick={() => dispatch(increment())}
          >
            increment
          </button>
          <p>{count}</p>
        </div>
        <div>
          <label>new user:</label>
          <input
            type="text"
            value={newUser}
            onChange={(e) => setNewUser(e.target.value)}
          ></input>
          <button onClick={addnewUser}>addnewuser</button>
        </div>
      </main>
    </div>
  );
}
export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    store.dispatch(setProfileData("babak"));
    store.dispatch(addUser("userdispatched from getserverside index page"));
    return {
      props: {},
    };
  }
);
